default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: <%= ENV['POSTGRES_USER_DEV'] %>
  password: <%= ENV['POSTGRES_PW_DEV'] %>
  database: car_diary_development
  url: <%= ENV['DATABASE_URL_DEV'] %>

test:
  <<: *default
  database: car_diary_test
  username: <%= ENV['POSTGRES_USER_DEV'] %>
  password: <%= ENV['POSTGRES_PW_DEV'] %>


production:
  <<: *default
  database: car_diary_production
  username: <%= ENV['DATABASE_USERNAME_PROD'] %>
  password: <%= ENV['DATABASE_PW_PROD'] %>
  host: <%= ENV['DATABASE_HOST_PROD'] %>
  url: <%= ENV['DATABASE_URL_PROD'] %>
